### ISSUE TITLE
Restore tabs no longer works

### ISSUE THREAD

**Issue by duck7000** [raelgc/gedit-restore-tabs#14]
I'm using Manjaro and after update glibc to 2.38-7 restore tabs no longer works

During this update i noticed that amtk get replaced by libgedit-amtk, gedit now uses libgedit-amtk as required.

I did install restore tabs as described here but it didn't work.

Restore tabs is still in plugins section of gedit and checked but tabs are not restored

**Comment by raelgc** [comment]
Hi @duck7000 and sorry for the late response.

Which is the Gnome version?

**Comment by duck7000** [comment]
I don't know, i don't use Gnome.
I use xfce and have gedit installed (version 46.1)

**Comment by raelgc** [comment]
I see. I'm still using Ubuntu `22.04`, which has version `41`. I'll try Ubuntu `23.10` in a VM.

**Comment by duck7000** [comment]
Oeps wrong button

**Comment by duck7000** [comment]
I started gedit on the terminal, opened a few files and closed gedit this gives some interesting errors:

```
Traceback (most recent call last):
  File "/home/ed/.local/share/gedit/plugins/restoretabs.py", line 88, in on_tab_added
    if document.is_untitled() and len(window.get_documents()) > 1:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'is_untitled'. Did you mean: 'is_untouched'?
Traceback (most recent call last):
  File "/home/ed/.local/share/gedit/plugins/restoretabs.py", line 88, in on_tab_added
    if document.is_untitled() and len(window.get_documents()) > 1:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'is_untitled'. Did you mean: 'is_untouched'?
Traceback (most recent call last):
  File "/home/ed/.local/share/gedit/plugins/restoretabs.py", line 88, in on_tab_added
    if document.is_untitled() and len(window.get_documents()) > 1:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'is_untitled'. Did you mean: 'is_untouched'?

```
I hope this may help you get started

**Comment by duck7000** [comment]
Are you still working on this, as your last reaction was from 27 November 2023?

**Comment by raelgc** [comment]
Not yet. Probably you should try, as suggested by the error, replace all `is_untitled` with `is_untouched` on `restoretabs.py` and check if it works.

**Comment by duck7000** [comment]
i tried that, result is the same.
Although it creates new problems with opening new files

**Comment by Batwam** [comment]
same issue here. If I replace `is_untitled` with `is_untouched`, I then get to the following error"
```py
Traceback (most recent call last):
  File "/home/user/.local/share/gedit/plugins/restoretabs.py", line 77, in on_window_show
    self.window.create_tab_from_location(location, None, 0, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'create_tab_from_location'. Did you mean: 'get_tab_from_location'?
```

looks like there have been changes to the gedit API as I can see that some files from gedit-plugins also stopped working. This plugin is very useful to me, if it isn't going to be maintained, may I suggest transferring it to the gedit-plugins maintainer?
https://gitlab.gnome.org/World/gedit/gedit-plugins/-/commits/master/plugins/sessionsaver/sessionsaver?ref_type=heads

**Comment by Batwam** [comment]
ok, I have managed to adress the missing 'create_tab_from_location' by replacing it with tab creation followed by document loading.
```py
                            tab = self.window.create_tab(True) #create new tab and jump_to it
                            tab.load_file(location, None, 0, 0, True) #GFile *location,*encoding,line_pos,column_pos,create
```
`is_untouched` isn't a like for like replacement for `is_untitled`. Not sure exactly what it does but it had the effect to automatically close the second tab on loadout. took me a while to figure out what was going on there! in the meantime, I have commented the lines out which means that I'm left with an extra "Untitled Document 1" tab on startup but it's still better than having to reopen all my tabs by hand!

see updated file here: https://github.com/Batwam/gedit-restore-tabs/blob/master/restoretabs.py
if anyone is able to find a replacement solution for `is_untitled` that would be amazing.

**Comment by Batwam** [comment]
ok, I think that I found a workaround to delete the Untitled Document tab. 
See explanations in the pull request above

**Comment by cfancsy** [comment]
Thank you for fixing this, I couldn't figure it out but with your changes it works again.

**Comment by Batwam** [comment]
yeah, it's a bit of a hack to be honest and I occasionally find that I have to select a file twice for it to open but still better than nothing as I can't live without this feature ;-)

**Comment by raelgc** [comment]
I just switched to Ubuntu 24.04 (was using 22.04). I've noticed that the default editor, Gnome Text Editor already has a session management (i.e., it restores previous opened files).

**Comment by Batwam** [comment]
Yeah, Text Editor does have tab management, however it doesn't have any plugin to include a terminal within the editor. That's the main reason I'm still using gedit as I use it (mostly) for coding scripts.

**Comment by raelgc** [comment]
I've merged the PR.

**Comment by Batwam** [comment]
@raelgc  suggest to close this issue
